#cloud-config
autoinstall:
  version: 1

  source:
    id: ubuntu-desktop-minimal # ubuntu-desktop-minimal is the default, but here for clarity
    search_drivers: true # true is the default, but here for clarity

  interactive-sections:
    # Network and locale seem to be already defined through the installer???
#    - network
#    - locale # although we configure it, confirm the configuration
    - storage

  identity:
    hostname: devaholics-test
    realname: Test User
    username: test
    # Use "openssl passwd -6" to generate this hash
    password: $6$D2v8LUU9.UMWWClx$2jClQqoGv.9kBwqeICBcwFwPRLFsH/2Q1F1IrRQCIHFHHtt0OIuH2Zb4vxRPWPPLC/tiSnoEFOknO7XpOwen00

  locale: en_US.UTF-8 # en_US.UTF-8 is the default, but here for clarity

  timezone: "Europe/Vienna"

  refresh-installer:
    update: true

  keyboard:
    layout: at

  codecs:
    install: true

  drivers:
    install: true

  oem:
    install: auto # auto is the default. it will be true for ubuntu-desktop systems

#  snaps:
#    - name: htop
#    - name: bitwarden
#    - name: slack
#    - name: code
#      classic: true

#  packages:
#    - curl
#    - vim
#    - git
#    - podman

  updates: all

  shutdown: reboot

  user-data:
    write_files:
      - path: /home/test/Desktop/manual-steps-to-finish-install.txt
        owner: 'test:test'
        defer: true
        content: |
          1. In GNOME, add your Google account
          2. In Googe Chrome, add your Google account
          3. Add SSH private keys (TODO setup basic config automated beforehand)
          4. Configure timers in Clocks to
            a. take a break
            b. use the standing desk
      - path: /home/test/Desktop/finish-setup.sh
        owner: 'test:test'
        permissions: '0700'
        defer: true
        source:
          uri: https://raw.githubusercontent.com/devaholics/ubuntu-autoinstall/refs/heads/main/finish-setup.sh
      - path: /home/test/.config/systemd/user/first-run.service
        owner: 'test:test'
        permissions: '0644'
        defer: true
        source:
          uri: https://raw.githubusercontent.com/devaholics/ubuntu-autoinstall/refs/heads/main/first-run.service
    runcmd:
      # 1. Enable lingering so the user's systemd manager starts at boot
      - [ loginctl, enable-linger, test ]
      # 2. Now we can enable the systemd service
      - [ systemctl, --user, -M, "test@", daemon-reload ]
      - [ systemctl, --user, -M, "test@", enable, first-run.service ]
